// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxZMAqpyweEFCZZUX0KIVnuGKbNzzgnl0',
    appId: '1:175166302776:web:4de9d578a7d743b3e2d4cd',
    messagingSenderId: '175166302776',
    projectId: 'darahcepat-app',
    authDomain: 'darahcepat-app.firebaseapp.com',
    storageBucket: 'darahcepat-app.firebasestorage.app',
    measurementId: 'G-CMGF8LBRY7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFzPUeSXC-U7IfL2mSgvF4OLnnX44BXMs',
    appId: '1:175166302776:android:c3d2550521a538a2e2d4cd',
    messagingSenderId: '175166302776',
    projectId: 'darahcepat-app',
    storageBucket: 'darahcepat-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrbe_nxVwxof3lPOQQ7MEQWMYsGDGKTpk',
    appId: '1:175166302776:ios:7bda2d4c552be86ce2d4cd',
    messagingSenderId: '175166302776',
    projectId: 'darahcepat-app',
    storageBucket: 'darahcepat-app.firebasestorage.app',
    iosBundleId: 'com.example.darahcepat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrbe_nxVwxof3lPOQQ7MEQWMYsGDGKTpk',
    appId: '1:175166302776:ios:7bda2d4c552be86ce2d4cd',
    messagingSenderId: '175166302776',
    projectId: 'darahcepat-app',
    storageBucket: 'darahcepat-app.firebasestorage.app',
    iosBundleId: 'com.example.darahcepat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxZMAqpyweEFCZZUX0KIVnuGKbNzzgnl0',
    appId: '1:175166302776:web:c4b939406867dcbde2d4cd',
    messagingSenderId: '175166302776',
    projectId: 'darahcepat-app',
    authDomain: 'darahcepat-app.firebaseapp.com',
    storageBucket: 'darahcepat-app.firebasestorage.app',
    measurementId: 'G-MTYKTXVZ8Y',
  );
}
